### ISSUE TITLE
Retrofit existing debian installation with TKLBAM 

### ISSUE THREAD

**Issue by cboulanger** [turnkeylinux/tklbam#2]
(see https://www.turnkeylinux.org/forum/support/20150820/retrofit-existing-debian-installation-tklbam)

I have tried to install TKLBAM on an existing Debian 7 Installations (Docker container) like so:
```
# wget -O - -q https://raw.github.com/turnkeylinux/tklbam/master/contrib/ez-apt-install.sh | PACKAGE=tklbam /bin/bash 
# apt-get install tklbam
# tkbam init MYSECRETAPIKEY
```
Then it will tell you that profile "Debian 7" has been downloaded and the a link to the Hub has been established. Doing a dry run revealed that all additions to the base Debian are saved.

However, trying to restore this backup in an exact copy of the Debian 7 machine (clone of the Docker container) gives me this error:

```
root@container2:~# tklbam restore 25
Executing Duplicity to download s3://s3-eu-west-1.amazonaws.com/tklbam-adsafdsaas to /tmp/tklbam-b4PY04
==============================================================================================================

// started squid: caching downloaded backup archives to /var/cache/tklbam/restore

Traceback (most recent call last):
  File "/usr/bin/tklbam", line 46, in <module>
    CliWrapper.main()
  File "/usr/lib/tklbam/cliwrapper.py", line 88, in main
    commands[command].main()
  File "/usr/lib/tklbam/cmd_restore.py", line 491, in main
    backup_extract_path = get_backup_extract()
  File "/usr/lib/tklbam/cmd_restore.py", line 463, in get_backup_extract
    downloader(raw_download_path, target, log=_print if not silent else None, debug=opt_debug, force=opt_force)
  File "/usr/lib/tklbam/duplicity.py", line 166, in __call__
    squid.start()
  File "/usr/lib/tklbam/squid.py", line 59, in start
    raise Error("%s failed to start\n" % SQUID_BIN + self.command.output)
squid.Error: /usr/lib/tklbam/deps/usr/sbin/tklbam-squid failed to start
FATAL: storeUfsDirParse: invalid size value
Squid Cache (Version 2.7.STABLE9): Terminated abnormally.
CPU Usage: 0.003 seconds = 0.002 user + 0.001 sys
Maximum Resident Size: 5536 KB
Page faults with physical i/o: 0
Aborted
Traceback (most recent call last):
  File "/usr/lib/tklbam/deps/usr/sbin/tklbam-squid", line 192, in <module>
    main()
  File "/usr/lib/tklbam/deps/usr/sbin/tklbam-squid", line 188, in main
    system("%s -f %s -z" % (squid_bin, conf_tmp.path))
  File "/usr/lib/python2.7/dist-packages/executil.py", line 56, in system
    raise ExecError(command, exitcode)
executil.ExecError: non-zero exitcode (134) for command: /usr/lib/tklbam/deps/usr/sbin/squid -f /tmp/tklbam-squid-conf-gWw287 -z
```

What might be the problem?

**Comment by cboulanger** [comment]
Duplicate of https://github.com/turnkeylinux/tracker/issues/502
